---
name: Release
on:
  push:
    branches:
    - main

jobs:
  generate-tag:
    name: Generate Tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install -g semantic-release
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: semantic-release -e
