---
name: Release
on:
  push:
    branches:
    - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install -g semantic-release
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: semantic-release -e

  build-docker:
    needs: release
    runs-on: ubuntu-latest
    name: Production build of the Docker Image
    steps:
    - uses: actions/checkout@v2
    - name: Pull
      run: git pull
    - name: Build the Docker image
      run: docker build -t robertfranzke/proxmox-backup-server-exporter:$(git describe --abbrev=0 --tags)  .
    - name: Log into registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login  -u ${{ secrets.REGISTRY_USER }} --password-stdin
    - name: Push image
      run: docker push robertfranzke/proxmox-backup-server-exporter:$(git describe --abbrev=0 --tags)
    - name: Tag latest
      run: docker tag robertfranzke/proxmox-backup-server-exporter:$(git describe --abbrev=0 --tags) robertfranzke/proxmox-backup-server-exporter:latest
    - name: Push latest
      run: robertfranzke/proxmox-backup-server-exporter:latest